config/routes.rb
Graf::Application.routes.draw do  resources :github_loads
  resources :companies
  resources :users
  resources :pull_requests
  resources :repos
  resources :github_loads
  resources :github_load_msgs
  resources :commits
  resources :orgs

  get '/analytics', to: 'analytics#index'
  get '/dashboard', to: 'dashboard#index'
  get '/report', to: 'report#index'

  post '/analytics_data' => 'api#analytics_data'
  post '/report_data' => 'api#report_data'

  get '/load', to: 'load#index'
  get '/start_load', to: 'load#start_load'
  get '/load_status', to: 'load#load_status'
  get '/delete_load_history', to: 'load#delete_load_history'
  get '/delete_all_data', to: 'load#delete_all_data'

  get '/release_notes', to: 'release_notes#index'
  get '/release_notes/:action', to: 'release_notes#:action'

  resources :graf_users
  resources :sessions
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'signup' => 'graf_users#new'

  get '/cache', to: 'cache#index'

  get '/info', to: 'info#info'
  get '/constants/:constant', to: 'constants#index'
  get '/clear_constants', to: 'constants#clear'

  root :to => 'dashboard#index'

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

end

app/models/repo.rb
class Repo < ActiveRecord::Base
  belongs_to :org
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  skip_before_filter :require_login
  before_action :set_repo, only: [:show, :edit, :update, :destroy]

  # GET /repos
  # GET /repos.json
  def index
    @repos = Repo.all
  end

  # GET /repos/1
  # GET /repos/1.json
  def show
  end

  # GET /repos/new
  def new
    @repo = Repo.new
  end

  # GET /repos/1/edit
  def edit
  end

  # POST /repos
  # POST /repos.json
  def create
    @repo = Repo.new(repo_params)

    respond_to do |format|
      if @repo.save
        format.html { redirect_to @repo, notice: 'Repo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @repo }
      else
        format.html { render action: 'new' }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repos/1
  # PATCH/PUT /repos/1.json
  def update
    respond_to do |format|
      if @repo.update(repo_params)
        format.html { redirect_to @repo, notice: 'Repo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repos/1
  # DELETE /repos/1.json
  def destroy
    @repo.destroy
    respond_to do |format|
      format.html { redirect_to repos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repo
      @repo = Repo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repo_params
      params.require(:repo).permit(:org_id, :git_id, :name, :full_name, :fork, :date_created, :date_updated, :date_pushed)
    end
end

app/views/repos/_form.html.erb
<%= form_for(@repo) do |f| %>
  <% if @repo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repo.errors.count, "error") %> prohibited this repo from being saved:</h2>

      <ul>
      <% @repo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :org_id %><br>
    <%= f.text_field :org_id %>
  </div>
  <div class="field">
    <%= f.label :git_id %><br>
    <%= f.number_field :git_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :fork %><br>
    <%= f.check_box :fork %>
  </div>
  <div class="field">
    <%= f.label :date_created %><br>
    <%= f.date_select :date_created %>
  </div>
  <div class="field">
    <%= f.label :date_updated %><br>
    <%= f.date_select :date_updated %>
  </div>
  <div class="field">
    <%= f.label :date_pushed %><br>
    <%= f.date_select :date_pushed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repos/edit.html.erb
<h1>Editing repo</h1>

<%= render 'form' %>

<%= link_to 'Show', @repo %> |
<%= link_to 'Back', repos_path %>

app/views/repos/index.html.erb
<h1>Listing repos</h1>

<table>
  <thead>
    <tr>
      <th>Org</th>
      <th>Git</th>
      <th>Name</th>
      <th>Full name</th>
      <th>Fork</th>
      <th>Date created</th>
      <th>Date updated</th>
      <th>Date pushed</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @repos.each do |repo| %>
      <tr>
        <td><%= repo.org %></td>
        <td><%= repo.git_id %></td>
        <td><%= repo.name %></td>
        <td><%= repo.full_name %></td>
        <td><%= repo.fork %></td>
        <td><%= repo.date_created %></td>
        <td><%= repo.date_updated %></td>
        <td><%= repo.date_pushed %></td>
        <td><%= link_to 'Show', repo %></td>
        <td><%= link_to 'Edit', edit_repo_path(repo) %></td>
        <td><%= link_to 'Destroy', repo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repo', new_repo_path %>

app/views/repos/new.html.erb
<h1>New repo</h1>

<%= render 'form' %>

<%= link_to 'Back', repos_path %>

app/views/repos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Org:</strong>
  <%= @repo.org %>
</p>

<p>
  <strong>Git:</strong>
  <%= @repo.git_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @repo.name %>
</p>

<p>
  <strong>Full name:</strong>
  <%= @repo.full_name %>
</p>

<p>
  <strong>Fork:</strong>
  <%= @repo.fork %>
</p>

<p>
  <strong>Date created:</strong>
  <%= @repo.date_created %>
</p>

<p>
  <strong>Date updated:</strong>
  <%= @repo.date_updated %>
</p>

<p>
  <strong>Date pushed:</strong>
  <%= @repo.date_pushed %>
</p>

<%= link_to 'Edit', edit_repo_path(@repo) %> |
<%= link_to 'Back', repos_path %>