config/routes.rb
Graf::Application.routes.draw do  resources :github_loads
  resources :companies
  resources :users
  resources :pull_requests
  resources :repos
  resources :github_loads
  resources :github_load_msgs
  resources :commits
  resources :orgs

  get '/analytics', to: 'analytics#index'
  get '/dashboard', to: 'dashboard#index'
  get '/report', to: 'report#index'

  post '/analytics_data' => 'api#analytics_data'
  post '/report_data' => 'api#report_data'

  get '/load', to: 'load#index'
  get '/start_load', to: 'load#start_load'
  get '/load_status', to: 'load#load_status'
  get '/delete_load_history', to: 'load#delete_load_history'
  get '/delete_all_data', to: 'load#delete_all_data'

  get '/release_notes', to: 'release_notes#index'
  get '/release_notes/:action', to: 'release_notes#:action'

  resources :graf_users
  resources :sessions
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'signup' => 'graf_users#new'

  get '/cache', to: 'cache#index'

  get '/info', to: 'info#info'
  get '/constants/:constant', to: 'constants#index'
  get '/clear_constants', to: 'constants#clear'

  root :to => 'dashboard#index'

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

end

app/models/github_load.rb
class GithubLoad < ActiveRecord::Base

  @@current_load = nil

  def self.log_current_msg(msg, log_level)
    if @@current_load 
      return @@current_load.log_msg(msg, log_level)
    end
  end

  def self.set_current_load(current_load)
    @@current_load = current_load
  end

  def log_msg(msg, log_level, log_date = Time.now)
    load_msg = GithubLoadMsg.create(:github_load_id => id,
      :msg => msg,
      :log_level => log_level,
      :log_date => log_date
      )
    puts load_msg
    return load_msg
  end

  def self.last_completed()
    GithubLoad.where("load_complete_time IS NOT NULL").order("load_complete_time DESC").first
  end

  def to_s
    return "GithubLoad=[load_start_time: #{load_start_time}, load_complete_time: #{load_complete_time}, initial_load: #{initial_load}]"
  end

end

app/controllers/github_loads_controller.rb
class GithubLoadsController < ApplicationController
  skip_before_filter :require_login
  before_action :set_github_load, only: [:show, :edit, :update, :destroy]

  # GET /github_loads
  # GET /github_loads.json
  def index
    @github_loads = GithubLoad.all
  end

  # GET /github_loads/1
  # GET /github_loads/1.json
  def show
  end

  # GET /github_loads/new
  def new
    @github_load = GithubLoad.new
  end

  # GET /github_loads/1/edit
  def edit
  end

  # POST /github_loads 
  # POST /github_loads.json
  def create
    @github_load = GithubLoad.new(github_load_params)

    respond_to do |format|
      if @github_load.save
        format.html { redirect_to @github_load, notice: 'Github load was successfully created.' }
        format.json { render action: 'show', status: :created, location: @github_load }
      else
        format.html { render action: 'new' }
        format.json { render json: @github_load.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /github_loads/1
  # PATCH/PUT /github_loads/1.json
  def update
    respond_to do |format|
      if @github_load.update(github_load_params)
        format.html { redirect_to @github_load, notice: 'Github load was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @github_load.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /github_loads/1
  # DELETE /github_loads/1.json
  def destroy
    @github_load.destroy
    respond_to do |format|
      format.html { redirect_to github_loads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_github_load
      @github_load = GithubLoad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def github_load_params
      params.require(:github_load).permit(:load_start_time, :load_complete_time, :initial_load)
    end
end

app/views/github_loads/_form.html.erb
<%= form_for(@github_load) do |f| %>
  <% if @github_load.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@github_load.errors.count, "error") %> prohibited this github_load from being saved:</h2>

      <ul>
      <% @github_load.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :load_start_time %><br>
    <%= f.datetime_select :load_start_time %>
  </div>
  <div class="field">
    <%= f.label :load_complete_time %><br>
    <%= f.datetime_select :load_complete_time %>
  </div>
  <div class="field">
    <%= f.label :initial_load %><br>
    <%= f.check_box :initial_load %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/github_loads/edit.html.erb
<h1>Editing github_load</h1>

<%= render 'form' %>

<%= link_to 'Show', @github_load %> |
<%= link_to 'Back', github_loads_path %>

app/views/github_loads/index.html.erb
<h1>Listing github_loads</h1>

<table>
  <thead>
    <tr>
      <th>Load start time</th>
      <th>Load complete time</th>
      <th>Initial load</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @github_loads.each do |github_load| %>
      <tr>
        <td><%= github_load.load_start_time %></td>
        <td><%= github_load.load_complete_time %></td>
        <td><%= github_load.initial_load %></td>
        <td><%= link_to 'Show', github_load %></td>
        <td><%= link_to 'Edit', edit_github_load_path(github_load) %></td>
        <td><%= link_to 'Destroy', github_load, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Github load', new_github_load_path %>

app/views/github_loads/new.html.erb
<h1>New github_load</h1>

<%= render 'form' %>

<%= link_to 'Back', github_loads_path %>

app/views/github_loads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Load start time:</strong>
  <%= @github_load.load_start_time %>
</p>

<p>
  <strong>Load complete time:</strong>
  <%= @github_load.load_complete_time %>
</p>

<p>
  <strong>Initial load:</strong>
  <%= @github_load.initial_load %>
</p>

<%= link_to 'Edit', edit_github_load_path(@github_load) %> |
<%= link_to 'Back', github_loads_path %>

<%# TODO: Include GithubLoadMsgs here for this load %>